/* Allegro datafile object indexes, produced by grabber v4.0.3 (RC2), MSVC */
/* Datafile: c:\Projecten\CS2D\graphics.dat */
/* Date: Fri Jul 23 22:50:15 2004 */
/* Do not hand edit! */

#define CLOUD_SHADOW01                   0        /* BMP  */
#define CLOUD_SHADOW02                   1        /* BMP  */
#define CLOUD_SHADOW03                   2        /* BMP  */
#define EDITOR_BLOCKED                   3        /* BMP  */
#define MENU_SHELL                       4        /* BMP  */
#define MOUSE                            5        /* BMP  */
#define PLAYER_ARCTIC                    6        /* BMP  */
#define PLAYER_GIGN                      7        /* BMP  */
#define PLAYER_GSG9                      8        /* BMP  */
#define PLAYER_LEET                      9        /* BMP  */
#define PLAYER_SAS                       10       /* BMP  */
#define PLAYER_URBAN                     11       /* BMP  */
#define SPRITE_C4                        12       /* BMP  */
#define SPRITE_EXPLO001                  13       /* BMP  */
#define SPRITE_EXPLO002                  14       /* BMP  */
#define SPRITE_EXPLO003                  15       /* BMP  */
#define SPRITE_EXPLO004                  16       /* BMP  */
#define SPRITE_EXPLO005                  17       /* BMP  */
#define SPRITE_EXPLO006                  18       /* BMP  */
#define SPRITE_EXPLO007                  19       /* BMP  */
#define SPRITE_EXPLO008                  20       /* BMP  */
#define SPRITE_EXPLO009                  21       /* BMP  */
#define SPRITE_EXPLO010                  22       /* BMP  */
#define SPRITE_EXPLO011                  23       /* BMP  */
#define SPRITE_EXPLO012                  24       /* BMP  */
#define SPRITE_EXPLO013                  25       /* BMP  */
#define SPRITE_EXPLO014                  26       /* BMP  */
#define SPRITE_EXPLO015                  27       /* BMP  */
#define SPRITE_EXPLO016                  28       /* BMP  */
#define SPRITE_EXPLO017                  29       /* BMP  */
#define SPRITE_EXPLO018                  30       /* BMP  */
#define SPRITE_EXPLO019                  31       /* BMP  */
#define SPRITE_EXPLO020                  32       /* BMP  */
#define SPRITE_EXPLO021                  33       /* BMP  */
#define SPRITE_EXPLO022                  34       /* BMP  */
#define SPRITE_EXPLO023                  35       /* BMP  */
#define SPRITE_EXPLO024                  36       /* BMP  */
#define SPRITE_EXPLO025                  37       /* BMP  */
#define SPRITE_PLANT01                   38       /* BMP  */
#define SPRITE_PLANT02                   39       /* BMP  */
#define SPRITE_PLANT03                   40       /* BMP  */
#define SPRITE_PLANT04                   41       /* BMP  */
#define SPRITE_PLANT05                   42       /* BMP  */
#define SPRITE_PLANT06                   43       /* BMP  */
#define SPRITE_PUFF01                    44       /* BMP  */
#define SPRITE_PUFF02                    45       /* BMP  */
#define SPRITE_PUFF03                    46       /* BMP  */
#define SPRITE_PUFF04                    47       /* BMP  */
#define SPRITE_PUFF05                    48       /* BMP  */
#define SPRITE_PUFF06                    49       /* BMP  */
#define SPRITE_PUFF07                    50       /* BMP  */
#define SPRITE_PUFF08                    51       /* BMP  */
#define SPRITE_PUFF09                    52       /* BMP  */
#define SPRITE_PUFF10                    53       /* BMP  */
#define SPRITE_RAINDROP01                54       /* BMP  */
#define SPRITE_RAINDROP02                55       /* BMP  */
#define SPRITE_RAINDROP03                56       /* BMP  */
#define SPRITE_RAINDROP04                57       /* BMP  */
#define SPRITE_RAINDROP05                58       /* BMP  */
#define SPRITE_RAINDROP06                59       /* BMP  */
#define SPRITE_RAINDROP07                60       /* BMP  */
#define SPRITE_RAINDROP08                61       /* BMP  */
#define SPRITE_RAINDROP09                62       /* BMP  */
#define SPRITE_SMOKE01                   63       /* BMP  */
#define SPRITE_SMOKE02                   64       /* BMP  */
#define SPRITE_SMOKE03                   65       /* BMP  */
#define SPRITE_SMOKE04                   66       /* BMP  */
#define SPRITE_SMOKE05                   67       /* BMP  */
#define SPRITE_SMOKE06                   68       /* BMP  */
#define SPRITE_SMOKE07                   69       /* BMP  */
#define SPRITE_SMOKE08                   70       /* BMP  */
#define SPRITE_SMOKE09                   71       /* BMP  */
#define SPRITE_SMOKE10                   72       /* BMP  */
#define SPRITE_SMOKE11                   73       /* BMP  */
#define SPRITE_SMOKE12                   74       /* BMP  */
#define SPRITE_SMOKE13                   75       /* BMP  */
#define SPRITE_SMOKE14                   76       /* BMP  */
#define SPRITE_SMOKE15                   77       /* BMP  */
#define SPRITE_SMOKE16                   78       /* BMP  */
#define SPRITE_SMOKE17                   79       /* BMP  */
#define SPRITE_SMOKE18                   80       /* BMP  */
#define SPRITE_SMOKE19                   81       /* BMP  */
#define SPRITE_SMOKE20                   82       /* BMP  */
#define SPRITE_SMOKE21                   83       /* BMP  */
#define SPRITE_SMOKE22                   84       /* BMP  */
#define SPRITE_SMOKE23                   85       /* BMP  */
#define SPRITE_SMOKE24                   86       /* BMP  */
#define SPRITE_SMOKE25                   87       /* BMP  */
#define SPRITE_SMOKE26                   88       /* BMP  */
#define SPRITE_SMOKE27                   89       /* BMP  */
#define SPRITE_SMOKE28                   90       /* BMP  */
#define SPRITE_SMOKE29                   91       /* BMP  */
#define SPRITE_SMOKE30                   92       /* BMP  */
#define STEAM_DOWNLEFT                   93       /* BMP  */
#define STEAM_DOWNRIGHT                  94       /* BMP  */
#define STEAM_NOTPOWERED                 95       /* BMP  */
#define STEAM_UPLEFT                     96       /* BMP  */
#define STEAM_UPRIGHT                    97       /* BMP  */
#define TEST_FLARE                       98       /* BMP  */
#define WEAPON_AK47                      99       /* BMP  */
#define WEAPON_AK47_DROPPED              100      /* BMP  */
#define WEAPON_M4A1                      101      /* BMP  */
#define WEAPON_M4A1_DROPPED              102      /* BMP  */

